name: "TVmaze"
guid: "A4A488D0-17A3-4919-8D82-7F3DE4F6B209"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-tvmaze.png"
version: 11
targetAbi: "10.7.7.0"
framework: "net6.0"
owner: "jellyfin"
overview: "Get TV metadata from TVmaze"
description: >
  Get TV metadata from TVmaze

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.TvMaze.dll"
  - "TvMaze.Api.Client.dll"
  - "Flurl.dll"
  - "Flurl.Http.dll"
  - "Polly.dll"
changelog: |2-
  ### Code or Repo Maintenance ###
  - Use meta ci (#42) @crobibero

  ### CI & build changes ###
  - fix: meta ci workflows (#44) @h1dden-da3m0n
  - Use meta ci (#42) @crobibero
